Repository Team-ticku/ticku_FE, pull requests merged in 2025-02, with the labels that each got.

#8 [FEAT] 위로가기 버튼 추가
  public/images/TopScrollBtn2.png
  src/components/common/TopScrollBtn.jsx
Labels: 🎨 ui

#10 chore React의 no-unused-vars 규칙 비활성화
  eslint.config.js
Labels: chore

#17 [UI] 포트폴리오 메인 페이지 제작
  public/images/portadd.png
  src/components/common/portfolioPages/PortBox.jsx
  src/components/common/portfolioPages/PortButton.jsx
  src/components/common/portfolioPages/PortTitle.jsx
  src/pages/portfolioPages/PortfolioMainPage.jsx
Labels: 🎨 ui, 🐧 소현

#20 [CHORE] 폴더 위치 변경 및 테스트 파일 삭제
  src/components/portfolioPages/PortBox.jsx
  src/components/portfolioPages/PortButton.jsx
  src/components/portfolioPages/PortTitle.jsx
  src/pages/page.jsx
Labels: chore

#18 [UI] 하단 내비바 추가
  src/App.jsx
  src/components/common/bottomNavBar/BottomNavBar.jsx
  src/components/common/bottomNavBar/FontAwesome.jsx
  src/components/common/bottomNavBar/PlusModal.jsx
  src/main.jsx
Labels: 🎨 ui, 🐱 하은

#21 [UI] 메인페이지 제작하기
  src/App.jsx
  src/components/mainpage/LiveIndexChart.jsx
  src/components/mainpage/LiveSearchRank.jsx
  src/components/mainpage/MainPortfolio.jsx
  src/pages/mainpage/MainPage.jsx
  src/pages/portfolioPages/PortfolioMainPage.jsx
Labels: 🎨 ui, 🐻‍❄️ 은비

#26 [FEAT] 뒤로가기 크기 조정 가능, 경로 지정 가능
  src/components/common/BackButton.jsx
Labels: ✨ feat, 🐶 민정

#28 [CHORE] 폴더 이름 변경
  src/components/common/bottomNavBars/BottomNavBar.jsx
  src/components/common/bottomNavBars/FontAwesome.jsx
  src/components/common/bottomNavBars/PlusModal.jsx
Labels: 🐱 하은, chore
