Repository Team-ticku/ticku_FE, pull requests merged in 2025-03, with the labels that each got.

#27 [UI] 티코 메인 페이지 제작
  src/components/tickoPages/common/header/CharacterProfile.jsx
  src/components/tickoPages/common/header/Header.jsx
  src/components/tickoPages/tickoPage/ButtonMenu.jsx
  src/components/tickoPages/tickoPage/CharIntroduce.jsx
  src/pages/tickoPages/TickoPage.jsx
Labels: 🎨 ui, 🐱 하은

#29 [FIX] 하단 내브바 크기 수정
  src/components/common/bottomNavBars/BottomNavBar.jsx
Labels: 🔧 fix, 🐱 하은

#31 [REFACTOR] 코드 구조 개선
  src/App.jsx
  src/components/common/bottomNavBars/BottomNavBar.jsx
  src/main.jsx
Labels: ♻️ refactor, 🐱 하은

#32 [UI] 정보제공 페이지(기업 로고, 이름, 종목 코드, 현재 가격과 변화량 컴포넌트) 추가 및 라우팅 설정 수정
  src/components/information/CompanyInfo.jsx
  src/components/information/NavBtn.jsx
  src/components/information/Navigation.jsx
  src/pages/InformationPages/Chart.jsx
  src/pages/InformationPages/InformationPage.jsx
Labels: ♻️ refactor, 🎨 ui, 🐆 장우

#33 [FIX] 모달창 위치 수정
  src/components/common/bottomNavBars/PlusModal.jsx
Labels: 🔧 fix, 🐱 하은

#36 [UI] 마이페이지 제작
  .gitignore
  public/images/pencilicon.png
  public/images/portfolioicon.png
  public/images/scrapicon.png
  public/images/staricon.png
  src/App.jsx
  src/components/myPages/MyPageModal.jsx
  src/components/myPages/MyPageTable.jsx
  src/index.css
  src/pages/myPages/MyPage.jsx
Labels: 🎨 ui, 🐶 민정

#38 [UI] 북마크 높이, 넓이 조정 가능
  src/components/common/BookMark.jsx
Labels: 🎨 ui, 🐶 민정

#39 [UI] 기초 지식 설명 페이지 제작
  src/components/tickoPages/BasicWordPage/WordBody.jsx
  src/components/tickoPages/BasicWordPage/WordRouting.jsx
  src/components/tickoPages/common/SpeechBubble/ElseSpeechBubble.jsx
  src/components/tickoPages/common/SpeechBubble/SpeechBubble.jsx
  src/components/tickoPages/common/SpeechBubble/StartSpeechBubble.jsx
  src/components/tickoPages/common/header/Header.jsx
  src/components/tickoPages/common/menu/LinkButton.jsx
  src/components/tickoPages/common/menu/Menu.jsx
  src/components/tickoPages/tickoPage/ButtonMenu.jsx
  src/pages/tickoPages/BasicWordPage.jsx
  src/pages/tickoPages/TickoRouting.jsx
Labels: 🎨 ui, 🐱 하은

#41 [FIX] import 오류 수정
  src/App.jsx
Labels: 🔧 fix, 🐶 민정

#42 [UI] 공용 컴포넌트 뉴스 카드 제작
  src/components/common/BookMark.jsx
  src/components/common/NewsCard.jsx
Labels: ♻️ refactor, 🎨 ui, 🐶 민정

#44 [UI] 기업 목록 컴포넌트 추가
  src/components/information/CompanyList.jsx
Labels: 🎨 ui, 🐆 장우

#47 [UI] 정보 제공 - 기업 목록 페이지 제작
  public/images/Information/lg전자.png
  public/images/Information/삼성전자.png
  src/App.jsx
  src/components/common/SearchBar.jsx
  src/components/common/bottomNavBars/BottomNavBar.jsx
  src/components/information/CompanyList.jsx
  src/pages/InformationPages/InformationPage.jsx
  src/pages/InformationPages/List.jsx
Labels: ♻️ refactor, 🎨 ui, 🐆 장우

#48 [UI] 차트 설명 페이지 제작
  public/images/basicChartPage/fall.png
  public/images/basicChartPage/longfall.png
  public/images/basicChartPage/longrise.png
  public/images/basicChartPage/rise.png
  src/components/tickoPages/BasicChartPage/ChartBody.jsx
  src/components/tickoPages/BasicChartPage/ChartRouting.jsx
  src/components/tickoPages/BasicChartPage/ImgMenu.jsx
  src/components/tickoPages/BasicWordPage/WordBody.jsx
  src/components/tickoPages/common/SpeechBubble/SpeechBubble.jsx
  src/components/tickoPages/common/SpeechBubble/StartSpeechBubble.jsx
  src/components/tickoPages/common/header/Header.jsx
  src/components/tickoPages/common/menu/LinkButton.jsx
  src/components/tickoPages/common/menu/Menu.jsx
  src/pages/tickoPages/BasicChartPage.jsx
  src/pages/tickoPages/BasicWordPage.jsx
  src/pages/tickoPages/TickoRouting.jsx
Labels: 🎨 ui, ✨ feat, 🐱 하은

#51 [UI] 스크랩한 뉴스 페이지 제작
  src/App.jsx
  src/components/common/NewsCard.jsx
  src/components/common/Star.jsx
  src/pages/myPages/MyPage.jsx
  src/pages/myPages/ScrapNews.jsx
Labels: 🎨 ui, 🐶 민정

#56 [UI] 관심 기업 목록 페이지 제작
  src/App.jsx
  src/components/common/NewsCard.jsx
  src/components/information/CompanyList.jsx
  src/pages/myPages/FavoriteCompanies.jsx
  src/pages/myPages/MyPage.jsx
Labels: 🎨 ui, 🐶 민정

#60 [CHORE] 티코 페이지 관련 파일 관리
  src/App.jsx
  src/components/tickoPages/BasicChartPage/ChartRouting.jsx
  src/components/tickoPages/BasicWordPage/WordRouting.jsx
  src/components/tickoPages/basicAccountPage/AccountRouting.jsx
  src/components/tickoPages/basicChartPage/ChartBody.jsx
  src/components/tickoPages/basicChartPage/ImgMenu.jsx
  src/components/tickoPages/basicWordPage/WordBody.jsx
  src/pages/tickoPages/BasicAccountPage.jsx
  src/pages/tickoPages/BasicChartPage.jsx
  src/pages/tickoPages/BasicWordPage.jsx
  src/pages/tickoPages/TickoRouting.jsx
  src/pages/tickoPages/accountMenuPages/AccountMenuPage2.jsx
  src/pages/tickoPages/tickoMenuPages/BasicAccountPage.jsx
  src/pages/tickoPages/tickoMenuPages/BasicChartPage.jsx
  src/pages/tickoPages/tickoMenuPages/BasicWordPage.jsx
  src/routes/BottomNavBarRoutes.jsx
  src/routes/TotalRoutes.jsx
  src/routes/tickoPages/AccountMenuRoutes.jsx
  src/routes/tickoPages/ChartMenuRoutes.jsx
  src/routes/tickoPages/TickoMainRoutes.jsx
  src/routes/tickoPages/WordMenuRoutes.jsx
Labels: 🐱 하은, chore

#72 [UI] 커뮤니티 글 목록 페이지 제작
  public/images/comment.png
  public/images/heart.png
  public/images/heartline.png
  public/images/pencil.png
  src/components/common/UserProfile.jsx
  src/components/communityPage/postListPage/Stats.jsx
  src/components/communityPage/postListPage/Tags.jsx
  src/components/communityPage/postListPage/WriteBtn.jsx
  src/pages/communityPages/data.json
  src/pages/communityPages/postListPage/PostList.jsx
  src/pages/communityPages/postListPage/PostListItem.jsx
  src/pages/communityPages/postListPage/PostListPage.jsx
  src/pages/communityPages/user.json
  src/routes/BottomNavBarRoutes.jsx
Labels: 🎨 ui, ✨ feat, 🐻‍❄️ 은비

#66 [UI] 배당락일 캘린더 제작
  public/images/calen-arrow-after.png
  public/images/calen-arrow-before.png
  src/components/common/stockcalendarPages/Stockcalendar.jsx
  src/components/common/stockcalendarPages/StockcalendarSchedule.jsx
  src/pages/stockcalendarPages/StockcalenPages.jsx
Labels: 🎨 ui, 🐧 소현

#75 [UI] 내 포트폴리오 페이지 제작
  public/images/arrow.png
  public/images/pin-fill.png
  public/images/pin-outline.png
  src/components/myPages/MyPageModal.jsx
  src/components/myPages/MyPortfolioAccordion.jsx
  src/pages/myPages/MyPage.jsx
  src/pages/myPages/MyPortfolio.jsx
  src/routes/TotalRoutes.jsx
  src/routes/myPages/MyPageRoutes.jsx
Labels: 🎨 ui, ✨ feat, 🐶 민정

#79 [FIX] 기업 목록 페이지 버그 수정
  public/images/Information/NewsSampleImage.png
  public/images/Information/dongaLogo.png
  src/components/common/NewsCard.jsx
  src/pages/informationPages/InformationPage.jsx
  src/pages/informationPages/NewsPage.jsx
Labels: ♻️ refactor, 🐆 장우

#80 [UI] 로그인 페이지 제작
  src/pages/loginPage/LoginPage.jsx
  src/routes/TotalRoutes.jsx
  src/routes/loginPage/LoginRoutes.jsx
Labels: 🎨 ui, ✨ feat, 🐶 민정

#82 [UI] 회원가입 페이지 제작
  src/pages/joinPage/JoinPage.jsx
  src/pages/loginPage/LoginPage.jsx
  src/routes/TotalRoutes.jsx
  src/routes/joinPage/JoinRoutes.jsx
Labels: 🎨 ui, 🐶 민정

#83 [FEAT] 하단 내브바, 위로 가기 버튼에 display 속성 동적 할당
  src/components/common/TopScrollBtn.jsx
  src/components/common/bottomNavBars/BottomNavBar.jsx
  src/pages/informationPages/InformationPage.jsx
  src/pages/mainpage/MainPage.jsx
  src/pages/portfolioPages/PortfolioMainPage.jsx
  src/pages/tickoPages/TickoPage.jsx
Labels: ✨ feat, 🐱 하은

#84 [FEAT] 모달 내려가는 애니메이션 추가
  src/components/myPages/MyPageModal.jsx
Labels: ✨ feat, 🐶 민정

#85 [REFACTOR] 로그인 기능 추가
  src/pages/loginPage/LoginPage.jsx
Labels: ♻️ refactor, 🐶 민정

#86 [UI] 커뮤니티 글 보기 페이지 추가
  src/components/common/UserProfile.jsx
  src/components/communityPage/Button.jsx
  src/components/communityPage/TextInput.jsx
  src/components/communityPage/postListPage/Stats.jsx
  src/components/communityPage/postListPage/Tags.jsx
  src/components/communityPage/postViewPage/CommentList.jsx
  src/components/communityPage/postViewPage/CommentListItem.jsx
  src/components/communityPage/postViewPage/Post.jsx
  src/components/communityPage/postViewPage/PostBox.jsx
  src/components/communityPage/postViewPage/UserAndTag.jsx
  src/components/communityPage/postViewPage/WriteComment.jsx
  src/pages/communityPages/data.json
  src/pages/communityPages/postListPage/PostListPage.jsx
  src/pages/communityPages/postPage/PostViewPage.jsx
  src/routes/TotalRoutes.jsx
  src/routes/communityPages/PostViewRoutes.jsx
Labels: ♻️ refactor, 🎨 ui, ✨ feat, 🐻‍❄️ 은비

#88 [FEAT] 회원가입 기능 추가
  src/pages/joinPage/JoinPage.jsx
  src/pages/loginPage/LoginPage.jsx
  src/routes/TotalRoutes.jsx
Labels: ✨ feat, 🔧 fix, 🐶 민정, chore

#90 [UI] 앱 시작 페이지 제작
  src/components/common/bottomNavBars/BottomNavBar.jsx
  src/components/startPage/ExPageForm.jsx
  src/components/startPage/Instruction.jsx
  src/components/tickoPages/tickoPage/CharIntroduce.jsx
  src/pages/communityPages/postListPage/PostListPage.jsx
  src/pages/startPages/ExFullPages.jsx
  src/pages/startPages/ExplainPages/WelcomeEx.jsx
  src/pages/startPages/StartPage.jsx
  src/routes/BottomNavBarRoutes.jsx
Labels: 🎨 ui, ✨ feat, 🐱 하은

#89 [UI] 포트폴리오 제작 페이지 추가
  public/images/minus.png
  public/images/plus.png
  src/components/portfoliomakepage/PortMakeBox.jsx
  src/components/portfoliomakepage/PortMakeBtn.jsx
  src/components/portfoliomakepage/PortMakeModal.jsx
  src/components/portfoliopage/PortBox.jsx
  src/pages/portfolioPages/PortfolioMainPage.jsx
  src/routes/TotalRoutes.jsx
  src/routes/portfolioPages/PortfolioRoutes.jsx
Labels: 🎨 ui, 🐧 소현

#91 [UI] 커뮤니티 글 작성 페이지 제작
  eslint.config.js
  public/images/checkbox.png
  public/images/cross-mark.png
  public/images/down-arrow.png
  public/images/photo-gallery.png
  src/components/common/BackButton.jsx
  src/components/common/Button.jsx
  src/components/communityPage/Button.jsx
  src/components/communityPage/postWritePage/BottomBar.jsx
  src/components/communityPage/postWritePage/ContentInput.jsx
  src/components/communityPage/postWritePage/SelectTag.jsx
  src/components/communityPage/postWritePage/TitleInput.jsx
  src/components/communityPage/postWritePage/TopBar.jsx
  src/pages/communityPages/postWritePage/PostWritePage.jsx
  src/routes/TotalRoutes.jsx
  src/routes/communityPages/CommunityRoutes.jsx
Labels: 🎨 ui, ✨ feat, 🐻‍❄️ 은비

#93 [UI] 앱 시작 화면 내 캘린더 페이지 설명 추가
  src/pages/startPages/ExFullPages.jsx
  src/pages/startPages/StartPage.jsx
  src/pages/stockcalendarPages/StockcalenPages.jsx
  src/routes/BottomNavBarRoutes.jsx
Labels: 🎨 ui, 🐱 하은

#94 [UI] 커뮤니티 페이지 텍스트 줄바꿈 문제 해결
  src/components/common/BackButton.jsx
  src/components/common/UserProfile.jsx
  src/components/communityPage/postWritePage/BottomBar.jsx
  src/pages/communityPages/postWritePage/PostWritePage.jsx
Labels: 🎨 ui, 🐻‍❄️ 은비

#96 ui: 기업 로고 삭제
  src/components/information/CompanyInfo.jsx
  src/components/information/CompanyList.jsx
  src/pages/informationPages/Chart.jsx
  src/pages/informationPages/DividendPage.jsx
  src/pages/informationPages/Finance.jsx
  src/pages/informationPages/InformationPage.jsx
  src/pages/informationPages/List.jsx
  src/pages/informationPages/NewsPage.jsx
  src/pages/informationPages/Result.jsx
  src/pages/informationPages/Volume.jsx
  src/pages/myPages/FavoriteCompanies.jsx
Labels: 🎨 ui, 🐆 장우

#97 [FEAT] 백엔드 연결 코드 추가
  src/pages/loginPage/LoginPage.jsx
  src/pages/myPages/ScrapNews.jsx
Labels: ✨ feat, 🐶 민정

#98 [UI] 배당락일 캘린더 수정
  src/components/stockcalendarPages/Stockcalendar.jsx
  src/components/stockcalendarPages/StockcalendarSchedule.jsx
  src/pages/portfolioPages/PortfolioMakePage.jsx
  src/routes/BottomNavBarRoutes.jsx
Labels: ♻️ refactor, 🐧 소현

#99 [REFACTOR] 백엔드 API 경로 수정
  src/pages/joinPage/JoinPage.jsx
  src/pages/loginPage/LoginPage.jsx
Labels: ♻️ refactor, 🐶 민정

#100 UI/#19 stock calendar
  src/components/stockcalendarPages/Stockcalendar.jsx
  src/components/stockcalendarPages/StockcalendarSchedule.jsx
  src/pages/stockcalendarPages/StockcalenPages.jsx
  src/routes/BottomNavBarRoutes.jsx
Labels: ♻️ refactor, 🐧 소현

#101 [FEAT] 세부 설명 페이지 백엔드 연결
  src/components/tickoPages/common/header/Header.jsx
  src/pages/startPages/ExFullPages.jsx
  src/pages/tickoPages/tickoMenuPages/Explain.jsx
  src/routes/TotalRoutes.jsx
  src/routes/tickoPage/TickoMainRoutes.jsx
  src/routes/tickoPages/AccountMenuRoutes.jsx
  src/routes/tickoPages/ChartMenuRoutes.jsx
  src/routes/tickoPages/WordMenuRoutes.jsx
Labels: 🎨 ui, ✨ feat, 🐱 하은

#109 [FEAT] 배당락일 캘린더 백엔드 연결
  src/components/stockcalendarPages/Stockcalendar.jsx
  src/components/stockcalendarPages/StockcalendarSchedule.jsx
  src/pages/stockcalendarPages/StockcalenPages.jsx
Labels: ✨ feat, 🐆 장우

#111 [FEAT] 검색 API 연동 및 자동완성 기능 추가
  src/components/common/SearchBar.jsx
  src/pages/stockcalendarPages/StockcalenPages.jsx
Labels: 🎨 ui, ✨ feat, 🐻‍❄️ 은비

#115 [FEAT] 마이페이지 백엔드 API 연결
  src/components/myPages/MyPageModal.jsx
  src/pages/myPages/MyPage.jsx
Labels: ✨ feat, 🐶 민정

#117 [FEAT] 세부 설명 이동 경로 변경
  src/components/tickoPages/basicAccountPage/AccountBody.jsx
  src/components/tickoPages/basicAccountPage/menu/AccountBody2.jsx
  src/components/tickoPages/basicChartPage/ChartBody.jsx
  src/components/tickoPages/basicChartPage/ImgMenu.jsx
  src/components/tickoPages/basicWordPage/WordBody.jsx
  src/components/tickoPages/tickoPage/ButtonMenu.jsx
  src/pages/tickoPages/tickoMenuPages/Explain.jsx
Labels: 🎨 ui, ✨ feat, 🐱 하은

#118 [FEAT] 주가 정보 및 차트 추가
  src/components/common/SearchBar.jsx
  src/components/information/AllChart.jsx
  src/components/information/NavBtn.jsx
  src/components/information/Navigation.jsx
  src/components/information/useStockData.jsx
  src/pages/informationPages/Chart.jsx
  src/pages/informationPages/InformationPage.jsx
  src/pages/informationPages/Search.jsx
  vite.config.js
Labels: ✨ feat, 🐆 장우

#120 [FEAT] 관심기업 API 연결
  src/components/common/Star.jsx
  src/components/information/CompanyList.jsx
  src/pages/myPages/FavoriteCompanies.jsx
  src/pages/myPages/MyPage.jsx
Labels: ✨ feat, 🐶 민정, chore

#122 [FEAT] 포트폴리오 페이지 차트 제작
  src/components/portfoliomakepage/PortMakeBtn.jsx
  src/components/portfoliomakepage/PortMakeModal.jsx
  src/components/portfoliopage/PortBox.jsx
  src/components/portfoliopage/PortButtons.jsx
  src/pages/portfolioPages/PortfolioMainPage.jsx
Labels: ✨ feat, 🐧 소현

#123 [FEAT] 기업 재무 페이지 API 연결
  src/components/common/SearchBar.jsx
  src/components/information/FinanceInfo.jsx
  src/components/information/YearResult.jsx
  src/components/information/YearResultChart.jsx
  src/pages/informationPages/Finance.jsx
  src/pages/informationPages/InformationPage.jsx
Labels: ✨ feat, 🐆 장우

#124 [FEAT] 스크랩한 뉴스 삭제
  src/components/common/BookMark.jsx
  src/components/common/NewsCard.jsx
  src/pages/myPages/ScrapNews.jsx
Labels: ✨ feat, 🐶 민정

#127 [FEAT] 포트폴리오 차트 백엔드 연결
  src/components/portfoliopage/PortButtons.jsx
Labels: ✨ feat, 🐧 소현

#129 [FEAT] 거래량 페이지 API 연결
  src/components/common/SearchBar.jsx
  src/components/information/VolumeTable.jsx
  src/pages/informationPages/InformationPage.jsx
  src/pages/informationPages/NewsPage.jsx
  src/pages/informationPages/Result.jsx
  src/pages/informationPages/Volume.jsx
Labels: ✨ feat, 🐆 장우

#131 [FEAT]배당 페이지 api 연결
  src/components/common/SearchBar.jsx
  src/pages/informationPages/DividendPage.jsx
  src/pages/informationPages/InformationPage.jsx
Labels: ✨ feat, 🐆 장우

#134 [FEAT] 정보제공페이지 관심 목록 별 배치
  src/components/information/CompanyInfo.jsx
Labels: ✨ feat, 🐧 소현

#136 [FEAT] 실적 페이지 API 차트 및 테이블 연결
  src/components/common/SearchBar.jsx
  src/components/information/QuarterlySalesChart.jsx
  src/components/information/QuarterlyTable.jsx
  src/components/information/ResultTable.jsx
  src/components/information/SalesYearChart.jsx
  src/components/information/YQButton.jsx
  src/pages/informationPages/InformationPage.jsx
  src/pages/informationPages/Result.jsx
Labels: ✨ feat, 🐆 장우

#138 [FEAT] 메인페이지 실시간 검색어 순위 API 연동하기
  node_modules/.package-lock.json
  package-lock.json
  package.json
  src/components/mainpage/LiveSearchRank.jsx
Labels: ✨ feat, 🐻‍❄️ 은비

#139 [FEAT] 내 포트폴리오 API 연결
  src/components/myPages/MyPortfolioAccordion.jsx
  src/components/portfoliopage/PortBox.jsx
  src/pages/myPages/MyPortfolio.jsx
Labels: ✨ feat, 🐶 민정

#143 [FEAT] 뉴스 페이지 API 연결
  src/components/common/NewsCard.jsx
  src/components/common/SearchBar.jsx
  src/components/information/CompanyInfo.jsx
  src/pages/informationPages/InformationPage.jsx
  src/pages/informationPages/NewsPage.jsx
Labels: ✨ feat, 🐆 장우

#144 [FEAT] 대표 포트폴리오 API 연결
  src/components/mainpage/MainPortfolio.jsx
  src/components/myPages/MyPortfolioAccordion.jsx
Labels: ♻️ refactor, ✨ feat, 🐶 민정

#147 [FIX] 검색 엔진 수정
  src/components/common/NewsCard.jsx
  src/components/common/SearchBar.jsx
  src/components/information/NavBtn.jsx
  src/pages/informationPages/InformationPage.jsx
Labels: ♻️ refactor, 🐆 장우

#151 [FEAT] 뉴스 스크랩 저장 및 삭제
  src/components/common/BookMark.jsx
  src/components/common/NewsCard.jsx
  src/pages/informationPages/NewsPage.jsx
  src/pages/myPages/ScrapNews.jsx
Labels: ✨ feat, 🐆 장우

#148 [FEAT] 로그아웃 추가
  src/components/myPages/MyPageModal.jsx
Labels: ✨ feat, 🐶 민정

#155 [FIX] 차트 이미지 양 옆에 패딩 추가, 시작 페이지에서 기업 정보 나오는 문제 수정
  src/components/information/AllChart.jsx
  src/pages/informationPages/InformationPage.jsx
  src/pages/startPages/ExFullPages.jsx
Labels: 🔧 fix, 🐆 장우

#157 [UI] 앱 시작 화면 위치 수정
  src/components/startPage/ExPageForm.jsx
  src/pages/startPages/ExFullPages.jsx
  src/pages/startPages/StartPage.jsx
Labels: 🎨 ui, 🐱 하은

#159 [FEAT] UserProfile 컴포넌트 API연동
  src/components/common/UserProfile.jsx
Labels: ✨ feat

#162 [FEAT] 스크랩한 뉴스 API 연결
  src/components/common/BookMark.jsx
  src/components/common/NewsCard.jsx
  src/components/information/CompanyList.jsx
  src/pages/informationPages/NewsPage.jsx
  src/pages/myPages/FavoriteCompanies.jsx
  src/pages/myPages/ScrapNews.jsx
Labels: ♻️ refactor, ✨ feat, 🐶 민정

#163 [UI] 로고 및 캐릭터 배치
  public/images/logo.png
  public/images/logo_pic.png
  public/images/ticko.png
  src/components/information/InfoFirst.jsx
  src/components/startPage/Instruction.jsx
  src/components/tickoPages/tickoPage/CharIntroduce.jsx
  src/pages/joinPage/JoinPage.jsx
  src/pages/loginPage/LoginPage.jsx
  src/pages/startPages/ExplainPages/WelcomeEx.jsx
Labels: 🎨 ui, 🐱 하은

#165 [FEAT] 배당락일 캘린더 문구 추가
  src/components/stockcalendarPages/Stockcalendar.jsx
  src/components/stockcalendarPages/StockcalendarSchedule.jsx
Labels: ✨ feat, 🐧 소현

#168 [FEAT] 커뮤니티 페이지 api 연결
  public/images/check-box-fill.png
  public/images/check-box.png
  public/images/photo-gallery-fill.png
  src/components/common/UserProfile.jsx
  src/components/communityPage/postListPage/Stats.jsx
  src/components/communityPage/postListPage/Tags.jsx
  src/components/communityPage/postListPage/WriteBtn.jsx
  src/components/communityPage/postViewPage/Post.jsx
  src/components/communityPage/postViewPage/PostBox.jsx
  src/components/communityPage/postViewPage/UserAndTag.jsx
  src/components/communityPage/postViewPage/WriteComment.jsx
  src/components/communityPage/postWritePage/BottomBar.jsx
  src/components/communityPage/postWritePage/ContentInput.jsx
  src/components/communityPage/postWritePage/SelectTag.jsx
  src/components/communityPage/postWritePage/TitleInput.jsx
  src/components/communityPage/postWritePage/TopBar.jsx
  src/pages/communityPages/postListPage/PostList.jsx
  src/pages/communityPages/postListPage/PostListItem.jsx
  src/pages/communityPages/postListPage/PostListPage.jsx
  src/pages/communityPages/postPage/PostViewPage.jsx
  src/pages/communityPages/postWritePage/PostWritePage.jsx
Labels: ✨ feat, 🐻‍❄️ 은비

#169 [FIX] 커뮤니티 api 연결 수정
  src/components/common/UserProfile.jsx
  src/components/communityPage/postViewPage/CommentList.jsx
  src/components/communityPage/postViewPage/CommentListItem.jsx
  src/components/communityPage/postViewPage/PostBox.jsx
  src/components/myPages/MyPageModal.jsx
  src/components/stockcalendarPages/Stockcalendar.jsx
  src/pages/communityPages/postListPage/PostList.jsx
  src/pages/communityPages/postListPage/PostListItem.jsx
  src/pages/myPages/MyPage.jsx
Labels: ✨ feat, 🔧 fix, 🐻‍❄️ 은비

#172 [UI] 로그인 및 회원가입 페이지, 앱 시작 화면 수정
  src/pages/joinPage/JoinPage.jsx
  src/pages/loginPage/LoginPage.jsx
  src/pages/startPages/ExFullPages.jsx
Labels: 🎨 ui, 🐱 하은

#175 fix: 아이콘 활성화 조건 변경
  src/components/common/bottomNavBars/BottomNavBar.jsx
Labels: 🔧 fix, 🐱 하은

#176 [UI] 하단 슬라이드바 색 변경
  src/pages/startPages/StartPage.jsx
Labels: 🎨 ui, 🐱 하은

#177 [FEAT] 커뮤니티 및 메인페이지 ui, 기능 추가
  public/images/menu.png
  src/components/common/BackButton.jsx
  src/components/communityPage/TextInput.jsx
  src/components/communityPage/postListPage/PostDate.jsx
  src/components/communityPage/postListPage/Tags.jsx
  src/components/communityPage/postViewPage/CommentDate.jsx
  src/components/communityPage/postViewPage/CommentListItem.jsx
  src/components/communityPage/postViewPage/DelAndEdit.jsx
  src/components/communityPage/postViewPage/PostBox.jsx
  src/components/communityPage/postViewPage/Topbar.jsx
  src/components/communityPage/postViewPage/WriteComment.jsx
  src/components/communityPage/postWritePage/BottomBar.jsx
  src/components/communityPage/postWritePage/ContentInput.jsx
  src/components/communityPage/postWritePage/SelectTag.jsx
  src/components/communityPage/postWritePage/TitleInput.jsx
  src/components/mainpage/LiveIndexChart.jsx
  src/components/mainpage/LiveSearchRank.jsx
  src/components/mainpage/MainPortfolio.jsx
  src/pages/communityPages/EditPostPage.jsx
  src/pages/communityPages/postListPage/PostListItem.jsx
  src/pages/communityPages/postPage/PostViewPage.jsx
  src/routes/communityPages/CommunityRoutes.jsx
Labels: 🎨 ui, ✨ feat, 🐻‍❄️ 은비

#178 [UI] 메인 페이지 설명 문구 위치 조정
  src/pages/startPages/ExFullPages.jsx
Labels: 🎨 ui, 🐱 하은

#180 [UI] 누락된 테마 변경
  src/components/common/bottomNavBars/BottomNavBar.jsx
  src/components/mainpage/LiveSearchRank.jsx
Labels: 🎨 ui, 🐱 하은

#182 [FIX] 포트폴리오 페이지 수정
  src/components/portfoliomakepage/PortMakeBox.jsx
  src/components/portfoliomakepage/PortMakeBtn.jsx
  src/components/portfoliomakepage/PortMakeModal.jsx
Labels: 🔧 fix, 🐆 장우

#184 [FIX] 커뮤니티 페이지 연도, 시간 수정
  src/components/communityPage/postListPage/PostDate.jsx
  src/components/communityPage/postViewPage/CommentDate.jsx
Labels: 🔧 fix, 🐆 장우

#186 [FIX] 기업 정보 홈페이지 버그 수정
  src/components/information/FinanceInfo.jsx
Labels: 🔧 fix, 🐆 장우

#187 [REFACTOR] 경로명 변경
  src/App.jsx
Labels: ♻️ refactor, 🐱 하은

#188 [REFACTOR] width 변경
  src/components/myPage/MyPortfolioAccordion.jsx
Labels: ♻️ refactor, 🐶 민정

#190 [REFACTOR] 티코 페이지, 앱 시작 화면 페이지 코드 리팩토링
  src/components/startPage/ExFullPages.jsx
  src/components/startPage/ExPageForm.jsx
  src/components/startPage/Instruction.jsx
  src/components/startPage/WelcomeEx.jsx
  src/components/tickoPage/common/header/CharacterProfile.jsx
  src/components/tickoPage/common/header/Header.jsx
  src/components/tickoPage/common/speechBubble/ElseSpeechBubble.jsx
  src/components/tickoPage/tickoPage/ButtonMenu.jsx
  src/components/tickoPage/tickoPage/CharIntroduce.jsx
  src/components/tickoPage/tickoPage/Explain.jsx
  src/pages/startPage/StartPage.jsx
  src/routes/BottomNavBarRoutes.jsx
Labels: ♻️ refactor, 🐱 하은
